version: 2
project_name: ai_installer
builds:
  - id: default
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/installer
    binary: ai_installer
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
nfpms:
  - id: default
    file_name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    vendor: "AI Knowledge Library"
    homepage: "https://github.com/howlcipher/ai_knowledge_library"
    maintainer: "William Elias"
    description: "AI Knowledge Library Installer"
    formats:
      - deb
      - rpm

