include: [".agents"]
exclude: ["Makefile"]
defaults:
  -
    scope:
      path: "documentation"
    values:
      layout: "default"
  -
    scope:
      path: ".agents"
    values:
      layout: "default"
  -
    scope:
      path: "index.md"
    values:
      layout: "default"
  -
    scope:
      path: "GEMINI.md"
    values:
      layout: "default"
  -
    scope:
      path: "AGENTS.md"
    values:
      layout: "default"
  -
    scope:
      path: "CLAUDE.md"
    values:
      layout: "default"
  -
    scope:
      path: "change_log.md"
    values:
      layout: "default"
