#!/usr/bin/env python3
"""
generate_skills_manifest.py

Regenerates the auto generated skills manifest table in AGENTS.md from the
frontmatter of every SKILL.md in the agents skills directory. The manifest
gives agents without native skill discovery (such as Gemini CLI) a cheap
routing surface: name, description, and path for each skill.

Run after adding, removing, or renaming a skill:
    python scripts/generate_skills_manifest.py
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.core.skill_router import SkillRouter  # noqa: E402
from src.infrastructure.config_loader import default_loader  # noqa: E402

MANIFEST_START = "<!-- SKILLS_MANIFEST_START -->"
MANIFEST_END = "<!-- SKILLS_MANIFEST_END -->"


def build_manifest_table(skills) -> str:
    """Renders the skills as a markdown table."""
    lines = [
        MANIFEST_START,
        "| Skill | Description | Path |",
        "| --- | --- | --- |",
    ]
    repo_root = default_loader.get_repo_root()
    for skill in skills:
        rel_path = os.path.relpath(skill.path, repo_root)
        description = skill.description.replace("|", "\\|")
        lines.append(f"| {skill.name} | {description} | `{rel_path}` |")
    lines.append(MANIFEST_END)
    return "\n".join(lines)


def update_agents_md(agents_md_path: str, table: str) -> None:
    """Replaces the manifest block in AGENTS.md, or appends a new section."""
    with open(agents_md_path, "r", encoding="utf8") as f:
        content = f.read()

    if MANIFEST_START in content and MANIFEST_END in content:
        start = content.index(MANIFEST_START)
        end = content.index(MANIFEST_END) + len(MANIFEST_END)
        content = content[:start] + table + content[end:]
    else:
        section = (
            "\n## Skills Manifest\n\n"
            "Auto generated by `scripts/generate_skills_manifest.py`. "
            "Do not edit by hand. Consult the listed SKILL.md file whenever a "
            "task matches a skill's description.\n\n"
        )
        content = content.rstrip("\n") + "\n" + section + table + "\n"

    with open(agents_md_path, "w", encoding="utf8") as f:
        f.write(content)


def main():
    router = SkillRouter()
    if not router.skills:
        print(f"No skills found in {router.skills_dir}. Nothing to do.")
        sys.exit(1)

    agents_md_path = os.path.join(default_loader.get_repo_root(), "AGENTS.md")
    table = build_manifest_table(router.skills)
    update_agents_md(agents_md_path, table)
    print(f"Wrote manifest with {len(router.skills)} skills to {agents_md_path}")


if __name__ == "__main__":
    main()
